
services:
  # mysql:
  #   image: mysql:8
  #   container_name: dev_mysql
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: symfony
  #     MYSQL_USER: symfony
  #     MYSQL_PASSWORD: symfony
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

  # php:
  #   build:
  #     context: ./backend
  #     dockerfile: ../docker/php/Dockerfile
  #   container_name: dev_php
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - mysql


  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile
    container_name: react_vite
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

volumes:
  mysql_data:
